version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mbmbgo-api
    restart: always
    ports:
      - '3200:3000'  # Host:Container
    environment:
      PORT: 3000
      DB_HOST: 172.17.10.66
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_DATABASE: my_nest_app
      JWT_SECRET: mySuperSecretKey
      JWT_EXPIRES_IN: 1d
      NODE_ENV: production
      MAIL_USER: ixora@mbmb.gov.my
      MAIL_PASS: eipigyeqqknzltqf
      FRONTEND_URL: https://ixora.mbmb.gov.my
      SFTP_HOST: 172.17.10.66
      SFTP_PORT: 22
      SFTP_USER: ixora
      SFTP_PASS: mP82AprjHSzawDJ5
      SFTP_UPLOAD_DIR: /upload
    command: npm run start:prod

  migration:
    build: .
    depends_on:
      api:
        condition: service_started
    command: npm run migration:generate -- src/migrations/Init
    environment:
      DB_HOST: 172.17.10.66
      DB_PORT: 3306
      DB_USERNAME: ixora-db
      DB_PASSWORD: PGR2NNFdJDJZGShi
      DB_DATABASE: ixora-prod
