version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      NODE_ENV: development

  migration:
    command: npm run migration:generate -- src/migrations/Init
