import { MigrationInterface, QueryRunner } from "typeorm";

export class AlterProjectOwnership1760744139940 implements MigrationInterface {
    name = 'AlterProjectOwnership1760744139940'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_uploads_business\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_uploads_user\``);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` DROP FOREIGN KEY \`FK_docver_business\``);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` DROP FOREIGN KEY \`FK_docver_upload\``);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` DROP FOREIGN KEY \`FK_4cc061875e9eecc311a94b3e431\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP FOREIGN KEY \`FK_249680f5fbff3fcd1921062e54d\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP FOREIGN KEY \`FK_62832d1ff00d59952fe56a1a62b\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP FOREIGN KEY \`FK_781afb8a074223672a6061dd45b\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP FOREIGN KEY \`FK_c59319eb97908839e99aff62167\``);
        await queryRunner.query(`DROP INDEX \`IDX_business_registration_number\` ON \`businesses\``);
        await queryRunner.query(`DROP INDEX \`UQ_push_user_endpoint\` ON \`push_subscriptions\``);
        await queryRunner.query(`DROP INDEX \`IDX_push_user\` ON \`push_subscriptions\``);
        await queryRunner.query(`DROP INDEX \`IDX_push_endpoint\` ON \`push_subscriptions\``);
        await queryRunner.query(`DROP INDEX \`IDX_myskb_projects_biz_user_status\` ON \`myskb_projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_myskb_projects_ownerId\` ON \`myskb_projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_myskb_ownership_business_email\` ON \`myskb_ownerships\``);
        await queryRunner.query(`DROP INDEX \`IDX_myskb_project_owners_projectId\` ON \`myskb_project_owners\``);
        await queryRunner.query(`DROP INDEX \`IDX_myskb_project_owners_ownerUserId\` ON \`myskb_project_owners\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP COLUMN \`ownerId\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD \`createdBy\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastName\` \`lastName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profilePicture\` \`profilePicture\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`state\` \`state\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`postalcode\` \`postalcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferences\` \`preferences\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetToken\` \`resetToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetTokenExpiry\` \`resetTokenExpiry\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationToken\` \`verificationToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationTokenExpires\` \`verificationTokenExpires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` ADD UNIQUE INDEX \`IDX_c28ef5f61ba8521e7b5e6e3dfe\` (\`registrationNumber\`)`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`invitationTokenExpires\` \`invitationTokenExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP COLUMN \`storage\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD \`storage\` varchar(32) NOT NULL DEFAULT 'sftp'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`folder\` \`folder\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP COLUMN \`mimeType\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD \`mimeType\` varchar(128) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP COLUMN \`documentType\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD \`documentType\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`businessId\` \`businessId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedCompanyName\` \`extractedCompanyName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedRegistrationNumber\` \`extractedRegistrationNumber\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedExpiryDate\` \`extractedExpiryDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchCompanyName\` \`matchCompanyName\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchRegistrationNumber\` \`matchRegistrationNumber\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchExpiry\` \`matchExpiry\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`confidence\` \`confidence\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`reason\` \`reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`mbmbId\` \`mbmbId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`role\` \`role\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`status\` \`status\` varchar(32) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`callback_payment_url\` \`callback_payment_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`order_id_prefix\` \`order_id_prefix\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`environment\` \`environment\` varchar(32) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`keyHash\` \`keyHash\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`lastSeenAt\` \`lastSeenAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` CHANGE \`status\` \`status\` enum ('draft', 'submitted', 'approved', 'pending_payment', 'paid', 'rejected', 'expired', 'pending_renewal', 'project_completed', 'project_onhold', 'project_cancelled') NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`name\` \`name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`role\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`project\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`project\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`avatarUrl\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`avatarUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`lastSeenIso\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`lastSeenIso\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`scope\` \`scope\` enum ('project-only', 'full') NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`inviteToken\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`inviteToken\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteTokenExpires\` \`inviteTokenExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`myskb_project_owners\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_project_owners\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tranID\` \`tranID\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`domain\` \`domain\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`status\` \`status\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`amount\` \`amount\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`currency\` \`currency\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`paydate\` \`paydate\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`appcode\` \`appcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_code\` \`error_code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_desc\` \`error_desc\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`channel\` \`channel\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`extraP\` \`extraP\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`treq\` \`treq\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_id\` \`vendor_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_method\` \`vendor_method\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`callbackPaymentUrl\` \`callbackPaymentUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`skey\` \`skey\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`bill_no\` \`bill_no\` varchar(128) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_75502844fa7dcb6c057aec73ec9\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_ed47433c6474a917b3b0446471f\``);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`businessId\` \`businessId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAt\` \`paidAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAmount\` \`paidAmount\` decimal(12,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayTransactionId\` \`paymentGatewayTransactionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayRefNo\` \`paymentGatewayRefNo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayStatus\` \`paymentGatewayStatus\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`mbmbSubmittedAt\` \`mbmbSubmittedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_0a72b849753a046462b4c5a8ec2\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`invitedBy\` \`invitedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`token\` \`token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`tokenExpires\` \`tokenExpires\` timestamp NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_0008bdfd174e533a3f98bf9af1\` ON \`push_subscriptions\` (\`endpoint\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4cc061875e9eecc311a94b3e43\` ON \`push_subscriptions\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9c8a42b552ea8125bee461a470\` ON \`push_subscriptions\` (\`userId\`, \`endpoint\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0132d669677db32306d295d478\` ON \`myskb_projects\` (\`businessId\`, \`createdBy\`, \`status\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_66c9c8855a6d126aa81cd8695d\` ON \`myskb_ownerships\` (\`businessId\`, \`email\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3629eeae437e9a5c8093f2b81c\` ON \`myskb_project_owners\` (\`projectId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e2e8deebff475f85e2c1d8219e\` ON \`myskb_project_owners\` (\`ownerUserId\`)`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_b7be9862a3ab843c72d454cc4d4\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_632458210d8f0159857b0f05707\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` ADD CONSTRAINT \`FK_36045773d45ab0db1e2ca31fe43\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` ADD CONSTRAINT \`FK_b08ed232591300ad1075c1fbfcc\` FOREIGN KEY (\`uploadId\`) REFERENCES \`uploads\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` ADD CONSTRAINT \`FK_4cc061875e9eecc311a94b3e431\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD CONSTRAINT \`FK_781afb8a074223672a6061dd45b\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD CONSTRAINT \`FK_c59319eb97908839e99aff62167\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_75502844fa7dcb6c057aec73ec9\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_ed47433c6474a917b3b0446471f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_0a72b849753a046462b4c5a8ec2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_0a72b849753a046462b4c5a8ec2\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_ed47433c6474a917b3b0446471f\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_75502844fa7dcb6c057aec73ec9\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP FOREIGN KEY \`FK_c59319eb97908839e99aff62167\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP FOREIGN KEY \`FK_781afb8a074223672a6061dd45b\``);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` DROP FOREIGN KEY \`FK_4cc061875e9eecc311a94b3e431\``);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` DROP FOREIGN KEY \`FK_b08ed232591300ad1075c1fbfcc\``);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` DROP FOREIGN KEY \`FK_36045773d45ab0db1e2ca31fe43\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_632458210d8f0159857b0f05707\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_b7be9862a3ab843c72d454cc4d4\``);
        await queryRunner.query(`DROP INDEX \`IDX_e2e8deebff475f85e2c1d8219e\` ON \`myskb_project_owners\``);
        await queryRunner.query(`DROP INDEX \`IDX_3629eeae437e9a5c8093f2b81c\` ON \`myskb_project_owners\``);
        await queryRunner.query(`DROP INDEX \`IDX_66c9c8855a6d126aa81cd8695d\` ON \`myskb_ownerships\``);
        await queryRunner.query(`DROP INDEX \`IDX_0132d669677db32306d295d478\` ON \`myskb_projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_9c8a42b552ea8125bee461a470\` ON \`push_subscriptions\``);
        await queryRunner.query(`DROP INDEX \`IDX_4cc061875e9eecc311a94b3e43\` ON \`push_subscriptions\``);
        await queryRunner.query(`DROP INDEX \`IDX_0008bdfd174e533a3f98bf9af1\` ON \`push_subscriptions\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`tokenExpires\` \`tokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`token\` \`token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`invitedBy\` \`invitedBy\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_0a72b849753a046462b4c5a8ec2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`mbmbSubmittedAt\` \`mbmbSubmittedAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayStatus\` \`paymentGatewayStatus\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayRefNo\` \`paymentGatewayRefNo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayTransactionId\` \`paymentGatewayTransactionId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAmount\` \`paidAmount\` decimal(12,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAt\` \`paidAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`businessId\` \`businessId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_ed47433c6474a917b3b0446471f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_75502844fa7dcb6c057aec73ec9\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`bill_no\` \`bill_no\` varchar(128) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`skey\` \`skey\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`callbackPaymentUrl\` \`callbackPaymentUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_method\` \`vendor_method\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_id\` \`vendor_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`treq\` \`treq\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`extraP\` \`extraP\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`channel\` \`channel\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_desc\` \`error_desc\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_code\` \`error_code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`appcode\` \`appcode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`paydate\` \`paydate\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`currency\` \`currency\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`amount\` \`amount\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`status\` \`status\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`domain\` \`domain\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tranID\` \`tranID\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_project_owners\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_project_owners\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteTokenExpires\` \`inviteTokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`inviteToken\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`inviteToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`scope\` \`scope\` enum ('project-only', 'full') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`lastSeenIso\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`lastSeenIso\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`avatarUrl\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`avatarUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`project\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`project\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD \`role\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`name\` \`name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` CHANGE \`status\` \`status\` enum ('draft', 'submitted') NOT NULL DEFAULT ''draft''`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`lastSeenAt\` \`lastSeenAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`keyHash\` \`keyHash\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`environment\` \`environment\` varchar(32) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`order_id_prefix\` \`order_id_prefix\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`callback_payment_url\` \`callback_payment_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`status\` \`status\` varchar(32) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`role\` \`role\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`mbmbId\` \`mbmbId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`reason\` \`reason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`confidence\` \`confidence\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchExpiry\` \`matchExpiry\` tinyint(4) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchRegistrationNumber\` \`matchRegistrationNumber\` tinyint(4) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchCompanyName\` \`matchCompanyName\` tinyint(4) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedExpiryDate\` \`extractedExpiryDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedRegistrationNumber\` \`extractedRegistrationNumber\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedCompanyName\` \`extractedCompanyName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`businessId\` \`businessId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP COLUMN \`documentType\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD \`documentType\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP COLUMN \`mimeType\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD \`mimeType\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`folder\` \`folder\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP COLUMN \`storage\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD \`storage\` varchar(50) NOT NULL DEFAULT ''sftp''`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`invitationTokenExpires\` \`invitationTokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`businesses\` DROP INDEX \`IDX_c28ef5f61ba8521e7b5e6e3dfe\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationTokenExpires\` \`verificationTokenExpires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationToken\` \`verificationToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetTokenExpiry\` \`resetTokenExpiry\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetToken\` \`resetToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferences\` \`preferences\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`postalcode\` \`postalcode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`state\` \`state\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profilePicture\` \`profilePicture\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastName\` \`lastName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP COLUMN \`createdBy\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD \`ownerId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_myskb_project_owners_ownerUserId\` ON \`myskb_project_owners\` (\`ownerUserId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_myskb_project_owners_projectId\` ON \`myskb_project_owners\` (\`projectId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_myskb_ownership_business_email\` ON \`myskb_ownerships\` (\`businessId\`, \`email\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_myskb_projects_ownerId\` ON \`myskb_projects\` (\`ownerId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_myskb_projects_biz_user_status\` ON \`myskb_projects\` (\`businessId\`, \`userId\`, \`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_push_endpoint\` ON \`push_subscriptions\` (\`endpoint\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_push_user\` ON \`push_subscriptions\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_push_user_endpoint\` ON \`push_subscriptions\` (\`userId\`, \`endpoint\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_business_registration_number\` ON \`businesses\` (\`registrationNumber\`)`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD CONSTRAINT \`FK_c59319eb97908839e99aff62167\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD CONSTRAINT \`FK_781afb8a074223672a6061dd45b\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD CONSTRAINT \`FK_62832d1ff00d59952fe56a1a62b\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD CONSTRAINT \`FK_249680f5fbff3fcd1921062e54d\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` ADD CONSTRAINT \`FK_4cc061875e9eecc311a94b3e431\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` ADD CONSTRAINT \`FK_docver_upload\` FOREIGN KEY (\`uploadId\`) REFERENCES \`uploads\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` ADD CONSTRAINT \`FK_docver_business\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_uploads_user\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_uploads_business\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
