import { MigrationInterface, QueryRunner } from "typeorm";

export class AlterBusinessLAM1760748121082 implements MigrationInterface {
    name = 'AlterBusinessLAM1760748121082'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`businesses\` ADD \`lamNumber\` varchar(191) NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` ADD UNIQUE INDEX \`IDX_af97ff0afdb4c596db43205242\` (\`lamNumber\`)`);
        await queryRunner.query(`ALTER TABLE \`businesses\` ADD \`lamDocumentPath\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` ADD \`lamStatus\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` ADD \`lamVerifiedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastName\` \`lastName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profilePicture\` \`profilePicture\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`state\` \`state\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`postalcode\` \`postalcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferences\` \`preferences\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetToken\` \`resetToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetTokenExpiry\` \`resetTokenExpiry\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationToken\` \`verificationToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationTokenExpires\` \`verificationTokenExpires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`invitationTokenExpires\` \`invitationTokenExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_b7be9862a3ab843c72d454cc4d4\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_632458210d8f0159857b0f05707\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`folder\` \`folder\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`mimeType\` \`mimeType\` varchar(128) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`documentType\` \`documentType\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`businessId\` \`businessId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedCompanyName\` \`extractedCompanyName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedRegistrationNumber\` \`extractedRegistrationNumber\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedExpiryDate\` \`extractedExpiryDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchCompanyName\` \`matchCompanyName\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchRegistrationNumber\` \`matchRegistrationNumber\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchExpiry\` \`matchExpiry\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`confidence\` \`confidence\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`reason\` \`reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`mbmbId\` \`mbmbId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`role\` \`role\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`status\` \`status\` varchar(32) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`callback_payment_url\` \`callback_payment_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`order_id_prefix\` \`order_id_prefix\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`environment\` \`environment\` varchar(32) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`keyHash\` \`keyHash\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`lastSeenAt\` \`lastSeenAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP FOREIGN KEY \`FK_c59319eb97908839e99aff62167\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`name\` \`name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`role\` \`role\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`project\` \`project\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`avatarUrl\` \`avatarUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`lastSeenIso\` \`lastSeenIso\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`scope\` \`scope\` enum ('project-only', 'full') NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteToken\` \`inviteToken\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteTokenExpires\` \`inviteTokenExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tranID\` \`tranID\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`domain\` \`domain\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`status\` \`status\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`amount\` \`amount\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`currency\` \`currency\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`paydate\` \`paydate\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`appcode\` \`appcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_code\` \`error_code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_desc\` \`error_desc\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`channel\` \`channel\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`extraP\` \`extraP\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`treq\` \`treq\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_id\` \`vendor_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_method\` \`vendor_method\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`callbackPaymentUrl\` \`callbackPaymentUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`skey\` \`skey\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_75502844fa7dcb6c057aec73ec9\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_ed47433c6474a917b3b0446471f\``);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`businessId\` \`businessId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAt\` \`paidAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAmount\` \`paidAmount\` decimal(12,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayTransactionId\` \`paymentGatewayTransactionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayRefNo\` \`paymentGatewayRefNo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayStatus\` \`paymentGatewayStatus\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`mbmbSubmittedAt\` \`mbmbSubmittedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`bill_no\` \`bill_no\` varchar(128) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_0a72b849753a046462b4c5a8ec2\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`invitedBy\` \`invitedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`token\` \`token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`tokenExpires\` \`tokenExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_b7be9862a3ab843c72d454cc4d4\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_632458210d8f0159857b0f05707\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD CONSTRAINT \`FK_c59319eb97908839e99aff62167\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_75502844fa7dcb6c057aec73ec9\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_ed47433c6474a917b3b0446471f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_0a72b849753a046462b4c5a8ec2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_0a72b849753a046462b4c5a8ec2\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_ed47433c6474a917b3b0446471f\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_75502844fa7dcb6c057aec73ec9\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP FOREIGN KEY \`FK_c59319eb97908839e99aff62167\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_632458210d8f0159857b0f05707\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_b7be9862a3ab843c72d454cc4d4\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`tokenExpires\` \`tokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`token\` \`token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`invitedBy\` \`invitedBy\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_0a72b849753a046462b4c5a8ec2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`bill_no\` \`bill_no\` varchar(128) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`mbmbSubmittedAt\` \`mbmbSubmittedAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayStatus\` \`paymentGatewayStatus\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayRefNo\` \`paymentGatewayRefNo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayTransactionId\` \`paymentGatewayTransactionId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAmount\` \`paidAmount\` decimal(12,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAt\` \`paidAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`businessId\` \`businessId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_ed47433c6474a917b3b0446471f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_75502844fa7dcb6c057aec73ec9\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`skey\` \`skey\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`callbackPaymentUrl\` \`callbackPaymentUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_method\` \`vendor_method\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_id\` \`vendor_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`treq\` \`treq\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`extraP\` \`extraP\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`channel\` \`channel\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_desc\` \`error_desc\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_code\` \`error_code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`appcode\` \`appcode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`paydate\` \`paydate\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`currency\` \`currency\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`amount\` \`amount\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`status\` \`status\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`domain\` \`domain\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tranID\` \`tranID\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteTokenExpires\` \`inviteTokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteToken\` \`inviteToken\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`scope\` \`scope\` enum ('project-only', 'full') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`lastSeenIso\` \`lastSeenIso\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`avatarUrl\` \`avatarUrl\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`project\` \`project\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`role\` \`role\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`name\` \`name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD CONSTRAINT \`FK_c59319eb97908839e99aff62167\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`lastSeenAt\` \`lastSeenAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`keyHash\` \`keyHash\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`environment\` \`environment\` varchar(32) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`order_id_prefix\` \`order_id_prefix\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`callback_payment_url\` \`callback_payment_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`status\` \`status\` varchar(32) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`role\` \`role\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`mbmbId\` \`mbmbId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`reason\` \`reason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`confidence\` \`confidence\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchExpiry\` \`matchExpiry\` tinyint(1) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchRegistrationNumber\` \`matchRegistrationNumber\` tinyint(1) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchCompanyName\` \`matchCompanyName\` tinyint(1) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedExpiryDate\` \`extractedExpiryDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedRegistrationNumber\` \`extractedRegistrationNumber\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedCompanyName\` \`extractedCompanyName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`businessId\` \`businessId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`documentType\` \`documentType\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`mimeType\` \`mimeType\` varchar(128) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`folder\` \`folder\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_632458210d8f0159857b0f05707\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_b7be9862a3ab843c72d454cc4d4\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`invitationTokenExpires\` \`invitationTokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationTokenExpires\` \`verificationTokenExpires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationToken\` \`verificationToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetTokenExpiry\` \`resetTokenExpiry\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetToken\` \`resetToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferences\` \`preferences\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`postalcode\` \`postalcode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`state\` \`state\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profilePicture\` \`profilePicture\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastName\` \`lastName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`businesses\` DROP COLUMN \`lamVerifiedAt\``);
        await queryRunner.query(`ALTER TABLE \`businesses\` DROP COLUMN \`lamStatus\``);
        await queryRunner.query(`ALTER TABLE \`businesses\` DROP COLUMN \`lamDocumentPath\``);
        await queryRunner.query(`ALTER TABLE \`businesses\` DROP INDEX \`IDX_af97ff0afdb4c596db43205242\``);
        await queryRunner.query(`ALTER TABLE \`businesses\` DROP COLUMN \`lamNumber\``);
    }

}
