import { MigrationInterface, QueryRunner } from "typeorm";

export class AlterProjectTable1769230024142 implements MigrationInterface {
    name = 'AlterProjectTable1769230024142'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` DROP FOREIGN KEY \`FK_16d824025421d3fc1fe5be8a1c7\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` DROP FOREIGN KEY \`FK_7966565066a4c4a269124cd967e\``);
        await queryRunner.query(`ALTER TABLE \`billing_items\` DROP FOREIGN KEY \`billing_items_ibfk_1\``);
        await queryRunner.query(`DROP INDEX \`IDX_whatsapp_otps_phone_purpose_status\` ON \`whatsapp_otps\``);
        await queryRunner.query(`DROP INDEX \`UQ_review_workflow_stage\` ON \`review_workflow_stages\``);
        await queryRunner.query(`DROP INDEX \`IDX_review_workflow_stages_module\` ON \`review_workflow_stages\``);
        await queryRunner.query(`DROP INDEX \`UQ_review_workflow_stage_members_stage_user\` ON \`review_workflow_stage_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_myskb_project_owners_businessId\` ON \`myskb_project_owners\``);
        await queryRunner.query(`DROP INDEX \`billingId\` ON \`billing_items\``);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` ADD \`reportDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastName\` \`lastName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profilePicture\` \`profilePicture\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`state\` \`state\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`postalcode\` \`postalcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferences\` \`preferences\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetToken\` \`resetToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetTokenExpiry\` \`resetTokenExpiry\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationToken\` \`verificationToken\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationTokenExpires\` \`verificationTokenExpires\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`invitationTokenExpires\` \`invitationTokenExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamNumber\` \`lamNumber\` varchar(191) NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamDocumentPath\` \`lamDocumentPath\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamStatus\` \`lamStatus\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamVerifiedAt\` \`lamVerifiedAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamStatusReason\` \`lamStatusReason\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_b7be9862a3ab843c72d454cc4d4\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_632458210d8f0159857b0f05707\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`folder\` \`folder\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`mimeType\` \`mimeType\` varchar(128) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`documentType\` \`documentType\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`businessId\` \`businessId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedCompanyName\` \`extractedCompanyName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedRegistrationNumber\` \`extractedRegistrationNumber\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedExpiryDate\` \`extractedExpiryDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchCompanyName\` \`matchCompanyName\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchRegistrationNumber\` \`matchRegistrationNumber\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchExpiry\` \`matchExpiry\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`confidence\` \`confidence\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`reason\` \`reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` CHANGE \`lastSentAt\` \`lastSentAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` CHANGE \`messageId\` \`messageId\` varchar(128) NULL`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`mbmbId\` \`mbmbId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`role\` \`role\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`status\` \`status\` varchar(32) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`callback_payment_url\` \`callback_payment_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`order_id_prefix\` \`order_id_prefix\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`environment\` \`environment\` varchar(32) NULL`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`keyHash\` \`keyHash\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` CHANGE \`enabled\` \`enabled\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` CHANGE \`currentReviewStage\` \`currentReviewStage\` enum ('level1', 'level2', 'final') NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` CHANGE \`latitude\` \`latitude\` decimal(10,7) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` CHANGE \`longitude\` \`longitude\` decimal(10,7) NULL`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`lastSeenAt\` \`lastSeenAt\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tranID\` \`tranID\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`domain\` \`domain\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`status\` \`status\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`amount\` \`amount\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`currency\` \`currency\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`paydate\` \`paydate\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`appcode\` \`appcode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_code\` \`error_code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_desc\` \`error_desc\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`channel\` \`channel\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`extraP\` \`extraP\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`treq\` \`treq\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_id\` \`vendor_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_method\` \`vendor_method\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`callbackPaymentUrl\` \`callbackPaymentUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`skey\` \`skey\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP FOREIGN KEY \`FK_c59319eb97908839e99aff62167\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`name\` \`name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`role\` \`role\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`project\` \`project\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`avatarUrl\` \`avatarUrl\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`lastSeenIso\` \`lastSeenIso\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`scope\` \`scope\` enum ('project-only', 'full') NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteToken\` \`inviteToken\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteTokenExpires\` \`inviteTokenExpires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_75502844fa7dcb6c057aec73ec9\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_ed47433c6474a917b3b0446471f\``);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`businessId\` \`businessId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAt\` \`paidAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAmount\` \`paidAmount\` decimal(12,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayTransactionId\` \`paymentGatewayTransactionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayRefNo\` \`paymentGatewayRefNo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayStatus\` \`paymentGatewayStatus\` varchar(64) NULL`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`mbmbSubmittedAt\` \`mbmbSubmittedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`bill_no\` \`bill_no\` varchar(128) NULL`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`status\` \`status\` enum ('CREATED', 'PAID', 'UNPAID', 'SUCCESS') NOT NULL DEFAULT 'CREATED'`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_0a72b849753a046462b4c5a8ec2\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`invitedBy\` \`invitedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`token\` \`token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`tokenExpires\` \`tokenExpires\` timestamp NULL`);
        await queryRunner.query(`CREATE INDEX \`IDX_1ae43959b537b7a1fb2ce96247\` ON \`whatsapp_otps\` (\`phone\`, \`purpose\`, \`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_321d05c97c4d9d8ac629490c27\` ON \`review_workflow_stages\` (\`module\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_0666de40e686d3f24e04e78826\` ON \`review_workflow_stages\` (\`module\`, \`stage\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d257b2a12621dd0653e4a5ef8c\` ON \`review_workflow_stage_members\` (\`stage_id\`, \`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_6cb4d781f45b93785bbe245379\` ON \`myskb_project_owners\` (\`businessId\`)`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_b7be9862a3ab843c72d454cc4d4\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_632458210d8f0159857b0f05707\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` ADD CONSTRAINT \`FK_16d824025421d3fc1fe5be8a1c7\` FOREIGN KEY (\`stage_id\`) REFERENCES \`review_workflow_stages\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` ADD CONSTRAINT \`FK_7966565066a4c4a269124cd967e\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD CONSTRAINT \`FK_c59319eb97908839e99aff62167\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_75502844fa7dcb6c057aec73ec9\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_ed47433c6474a917b3b0446471f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` ADD CONSTRAINT \`FK_12cd954c5fe58b742dd810062f4\` FOREIGN KEY (\`billingId\`) REFERENCES \`billings\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_0a72b849753a046462b4c5a8ec2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_0a72b849753a046462b4c5a8ec2\``);
        await queryRunner.query(`ALTER TABLE \`billing_items\` DROP FOREIGN KEY \`FK_12cd954c5fe58b742dd810062f4\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_ed47433c6474a917b3b0446471f\``);
        await queryRunner.query(`ALTER TABLE \`billings\` DROP FOREIGN KEY \`FK_75502844fa7dcb6c057aec73ec9\``);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` DROP FOREIGN KEY \`FK_c59319eb97908839e99aff62167\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` DROP FOREIGN KEY \`FK_7966565066a4c4a269124cd967e\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` DROP FOREIGN KEY \`FK_16d824025421d3fc1fe5be8a1c7\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_632458210d8f0159857b0f05707\``);
        await queryRunner.query(`ALTER TABLE \`uploads\` DROP FOREIGN KEY \`FK_b7be9862a3ab843c72d454cc4d4\``);
        await queryRunner.query(`DROP INDEX \`IDX_6cb4d781f45b93785bbe245379\` ON \`myskb_project_owners\``);
        await queryRunner.query(`DROP INDEX \`IDX_d257b2a12621dd0653e4a5ef8c\` ON \`review_workflow_stage_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_0666de40e686d3f24e04e78826\` ON \`review_workflow_stages\``);
        await queryRunner.query(`DROP INDEX \`IDX_321d05c97c4d9d8ac629490c27\` ON \`review_workflow_stages\``);
        await queryRunner.query(`DROP INDEX \`IDX_1ae43959b537b7a1fb2ce96247\` ON \`whatsapp_otps\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`tokenExpires\` \`tokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`token\` \`token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`invitedBy\` \`invitedBy\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_0a72b849753a046462b4c5a8ec2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`updatedAt\` \`updatedAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`status\` \`status\` enum ('CREATED', 'PAID', 'UNPAID', 'SUCCESS') NULL DEFAULT ''CREATED''`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` CHANGE \`bill_no\` \`bill_no\` varchar(128) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`mbmbSubmittedAt\` \`mbmbSubmittedAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayStatus\` \`paymentGatewayStatus\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayRefNo\` \`paymentGatewayRefNo\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paymentGatewayTransactionId\` \`paymentGatewayTransactionId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAmount\` \`paidAmount\` decimal(12,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`paidAt\` \`paidAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` CHANGE \`businessId\` \`businessId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_ed47433c6474a917b3b0446471f\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`billings\` ADD CONSTRAINT \`FK_75502844fa7dcb6c057aec73ec9\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteTokenExpires\` \`inviteTokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`inviteToken\` \`inviteToken\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`scope\` \`scope\` enum ('project-only', 'full') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`lastSeenIso\` \`lastSeenIso\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`avatarUrl\` \`avatarUrl\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`project\` \`project\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`role\` \`role\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`name\` \`name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_ownerships\` ADD CONSTRAINT \`FK_c59319eb97908839e99aff62167\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`skey\` \`skey\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`callbackPaymentUrl\` \`callbackPaymentUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_method\` \`vendor_method\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`vendor_id\` \`vendor_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`user_id\` \`user_id\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`treq\` \`treq\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`extraP\` \`extraP\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`channel\` \`channel\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_desc\` \`error_desc\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`error_code\` \`error_code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`appcode\` \`appcode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`paydate\` \`paydate\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`currency\` \`currency\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`amount\` \`amount\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`status\` \`status\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`domain\` \`domain\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`tranID\` \`tranID\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`lastSeenAt\` \`lastSeenAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`push_subscriptions\` CHANGE \`userAgent\` \`userAgent\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` CHANGE \`longitude\` \`longitude\` decimal(10,7) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` CHANGE \`latitude\` \`latitude\` decimal(10,7) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` CHANGE \`currentReviewStage\` \`currentReviewStage\` enum ('level1', 'level2', 'final') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stages\` CHANGE \`enabled\` \`enabled\` tinyint(1) NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`keyHash\` \`keyHash\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`environment\` \`environment\` varchar(32) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`order_id_prefix\` \`order_id_prefix\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`callback_payment_url\` \`callback_payment_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`status\` \`status\` varchar(32) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`role\` \`role\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`vendors\` CHANGE \`mbmbId\` \`mbmbId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` ADD \`updatedAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` ADD \`createdAt\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` CHANGE \`messageId\` \`messageId\` varchar(128) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`whatsapp_otps\` CHANGE \`lastSentAt\` \`lastSentAt\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`reason\` \`reason\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`confidence\` \`confidence\` decimal(5,2) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchExpiry\` \`matchExpiry\` tinyint(1) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchRegistrationNumber\` \`matchRegistrationNumber\` tinyint(1) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`matchCompanyName\` \`matchCompanyName\` tinyint(1) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedExpiryDate\` \`extractedExpiryDate\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedRegistrationNumber\` \`extractedRegistrationNumber\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`document_verifications\` CHANGE \`extractedCompanyName\` \`extractedCompanyName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`businessId\` \`businessId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`documentType\` \`documentType\` varchar(64) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`mimeType\` \`mimeType\` varchar(128) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` CHANGE \`folder\` \`folder\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_632458210d8f0159857b0f05707\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`uploads\` ADD CONSTRAINT \`FK_b7be9862a3ab843c72d454cc4d4\` FOREIGN KEY (\`businessId\`) REFERENCES \`businesses\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamStatusReason\` \`lamStatusReason\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamVerifiedAt\` \`lamVerifiedAt\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamStatus\` \`lamStatus\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamDocumentPath\` \`lamDocumentPath\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`lamNumber\` \`lamNumber\` varchar(191) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`businesses\` CHANGE \`invitationTokenExpires\` \`invitationTokenExpires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationTokenExpires\` \`verificationTokenExpires\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`verificationToken\` \`verificationToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetTokenExpiry\` \`resetTokenExpiry\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`resetToken\` \`resetToken\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`preferences\` \`preferences\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`dateOfBirth\` \`dateOfBirth\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`country\` \`country\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`postalcode\` \`postalcode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`state\` \`state\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`bio\` \`bio\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`profilePicture\` \`profilePicture\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastLogin\` \`lastLogin\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`lastName\` \`lastName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`username\` \`username\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`myskb_projects\` DROP COLUMN \`reportDate\``);
        await queryRunner.query(`CREATE INDEX \`billingId\` ON \`billing_items\` (\`billingId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_myskb_project_owners_businessId\` ON \`myskb_project_owners\` (\`businessId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_review_workflow_stage_members_stage_user\` ON \`review_workflow_stage_members\` (\`stage_id\`, \`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_review_workflow_stages_module\` ON \`review_workflow_stages\` (\`module\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_review_workflow_stage\` ON \`review_workflow_stages\` (\`module\`, \`stage\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_whatsapp_otps_phone_purpose_status\` ON \`whatsapp_otps\` (\`phone\`, \`purpose\`, \`status\`)`);
        await queryRunner.query(`ALTER TABLE \`billing_items\` ADD CONSTRAINT \`billing_items_ibfk_1\` FOREIGN KEY (\`billingId\`) REFERENCES \`billings\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` ADD CONSTRAINT \`FK_7966565066a4c4a269124cd967e\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`review_workflow_stage_members\` ADD CONSTRAINT \`FK_16d824025421d3fc1fe5be8a1c7\` FOREIGN KEY (\`stage_id\`) REFERENCES \`review_workflow_stages\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
    }

}
